Load default configs from .swfrc
ktonon/aws-swf pull request #3
Opened 2016-10-19 14:59 UTC by sliz1

2016-10-19 18:11 UTC, sliz1 commented
ping @ktonon

2016-10-20 19:17 UTC, ktonon commented
Yeah, sorry, I wasn't clear in the card on trello. These values should not be set at all. When defining an activity on AWS SWF, the default values can be defined there.

2016-10-20 19:17 UTC, ktonon requested changes

2016-10-20 19:17 UTC, ktonon commented on lib/decision-response.js
> +        ta.heartbeatTimeout = scheduleAttributes.heartbeatTimeout || config.heartbeatTimeout;
This whole section should just be removed

2016-10-24 17:50 UTC, sliz1 commented
Activity types and workflow types with all required defaults are created under the domain `content-service-staging` using SWF configs generated by https://github.com/Brightspace/d2l-content-service-swf-decider/pull/20

2016-10-24 18:51 UTC, sliz1 commented
ping @ktonon I think this PR should be safe to merge now, since we've already created types with all required defaults on AWS. Also, this shouldn't be used by decider until we change the aws-swf's git sha in the decider's package.json

2016-11-02 18:48 UTC, merged